[package]
name = "slack_client"
version = "0.1.0"
authors = ["SAWADA Tadashi <cesare@mayverse.jp>"]

[[bin]]
name = "list_conversations"
path = "src/bin/list_conversations.rs"

[[bin]]
name = "post_message"
path = "src/bin/post_message.rs"

[[bin]]
name = "rtm"
path = "src/bin/rtm.rs"

[[bin]]
name = "show_identity"
path = "src/bin/show_identity.rs"

[dependencies]
futures = "0.1.23"
http = "0.1.10"
hyper = "0.12.9"
hyper-tls = "0.3.0"
serde = "1.0.76"
serde_derive = "1.0.76"
serde_json = "1.0.26"
tokio = "0.1.8"
url = "1.7.1"
